baseurl = "http://localhost/"
languageCode = "en-us"
title = "Thunder Rabbit"
theme = "purehugo-tr"
MetaDataFormat = "yaml"
[params]
    twitterName = "thunderrabbit"
    githubName = "thunderrabbit"
    description = "keep pushing the limits"
[permalinks]
    journal = "/journal/:year/:month/:day/:title/"
